### ISSUE TITLE
is RobertaNumericalizeProcessor  needed ?

### ISSUE THREAD

**Issue by mrT23** [devkosal/tutorials#6]
Hi @devkosal, very nice repo

I noticed that 'RobertaNumericalizeProcessor'  is defined, but not used anywhere in:

> Using RoBERTa with Fastai Tutorial.ipynb

isn't the Numericalize processor needed?

Thanks,
Tal

**Comment by devkosal** [comment]
Hi Tal. Good catch. Since `RobertaNumericalizeProcessor` doesn't add anything on top of `NumericalizeProcessor`, either can work in the `get_roberta_processor` method. Hence, why it was previously unused in lieu of `NumericalizeProcessor`. However, I modified and updated [the notebook](https://github.com/devkosal/fastai_roberta/blob/master/fastai_roberta_imdb/Using%20RoBERTa%20with%20Fastai%20Tutorial.ipynb) to now use the `RobertaNumericalizeProcessor` instead to prevent future confusion.

**Comment by mrT23** [comment]
ok, thanks :)
